# Generated by Django 3.0.4 on 2020-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_adicionar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicionar',
            options={'verbose_name_plural': 'Adicionar'},
        ),
    ]
