# Generated by Django 3.0.4 on 2020-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200328_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionar',
            name='status',
            field=models.CharField(default='Pendente', max_length=200),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
