# Generated by Django 3.0.4 on 2020-03-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200328_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='adicionar',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='adicionar',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Categoria'),
        ),
    ]
