# Generated by Django 3.0.4 on 2020-03-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200328_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adicionar',
            old_name='status',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='status',
            new_name='tipo',
        ),
    ]
