# Generated by Django 3.0.4 on 2020-03-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200328_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionar',
            name='status',
            field=models.CharField(default='Pendente', max_length=200),
        ),
    ]
